/**
 * lib/cli/templates.js
 *
 * The harness template registry + auto-detection of project stack from
 * package.json and well-known config files. Used by `init` and `add`.
 *
 * Keeping this isolated lets us unit-test detectProject without spinning up
 * the whole CLI.
 */

import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";
import { exists } from "./utils.js";

// ─── Template registry ───
// `file` is the source filename in templates/. Templates with file=null are
// generated dynamically by `init` (project.md, rules.md).
export const TEMPLATES = {
  "project":       { file: null,                desc: "Project context (auto-generated by init)",        category: "core" },
  "rules":         { file: null,                desc: "Team rules & conventions (auto-generated by init)", category: "core" },
  "erd":           { file: "erd.md",            desc: "Database schema & entity relationships",           category: "data" },
  "architecture":  { file: "architecture.md",   desc: "System architecture & tech stack overview",        category: "system" },
  "api-spec":      { file: "api-spec.md",       desc: "API endpoints & contracts",                        category: "system" },
  "design-system": { file: "design-system.md",  desc: "Colors, typography, spacing, components",          category: "design" },
  "glossary":      { file: "glossary.md",       desc: "Domain terms, user roles, status flows",           category: "domain" },
  "user-flow":     { file: "user-flow.md",      desc: "User journeys, page map, error paths",             category: "domain" },
  "env-vars":      { file: "env-vars.md",       desc: "Environment variables & secrets guide",            category: "system" },
};

// ─── Project auto-detection ───
// Best-effort scan of the current working directory. All failures are silently
// swallowed — the resulting `info` always has the same shape, just with empty
// fields when detection misses. This keeps `init` runnable on any folder.
export async function detectProject() {
  const info = {
    name: "", description: "", stack: [], framework: "",
    hasTS: false, hasTailwind: false, hasI18n: false, hasAuth: false, hasDB: false,
    hasPayments: false, hasAI: false, deploy: "", dbName: "", authName: "", paymentName: "",
    components: [], apiRoutes: [], locales: [],
  };

  // package.json — primary source of truth for stack detection.
  try {
    const pkg = JSON.parse(await readFile(join(process.cwd(), "package.json"), "utf8"));
    info.name = pkg.name || "";
    info.description = pkg.description || "";
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };

    // Framework — first match wins. Order matters: SvelteKit before svelte, etc.
    if (allDeps["next"]) { info.framework = "Next.js"; info.stack.push("Next.js"); }
    else if (allDeps["nuxt"]) { info.framework = "Nuxt"; info.stack.push("Nuxt"); }
    else if (allDeps["react"]) { info.framework = "React"; info.stack.push("React"); }
    else if (allDeps["vue"]) { info.framework = "Vue"; info.stack.push("Vue"); }
    else if (allDeps["svelte"] || allDeps["@sveltejs/kit"]) { info.framework = "SvelteKit"; info.stack.push("SvelteKit"); }
    else if (allDeps["express"]) { info.framework = "Express"; info.stack.push("Express"); }

    // Core libraries
    if (allDeps["typescript"]) { info.hasTS = true; info.stack.push("TypeScript"); }
    if (allDeps["tailwindcss"]) { info.hasTailwind = true; info.stack.push("TailwindCSS"); }
    if (allDeps["framer-motion"]) info.stack.push("Framer Motion");

    // i18n
    if (allDeps["next-intl"] || allDeps["i18next"] || allDeps["react-intl"] || allDeps["next-i18next"]) {
      info.hasI18n = true; info.stack.push("i18n");
    }

    // Database
    if (allDeps["@supabase/supabase-js"]) { info.hasDB = true; info.dbName = "Supabase"; info.stack.push("Supabase"); }
    else if (allDeps["prisma"] || allDeps["@prisma/client"]) { info.hasDB = true; info.dbName = "Prisma"; info.stack.push("Prisma"); }
    else if (allDeps["drizzle-orm"]) { info.hasDB = true; info.dbName = "Drizzle"; info.stack.push("Drizzle"); }
    else if (allDeps["mongoose"]) { info.hasDB = true; info.dbName = "MongoDB"; info.stack.push("MongoDB"); }

    // Auth
    if (allDeps["next-auth"] || allDeps["@auth/core"]) { info.hasAuth = true; info.authName = "NextAuth"; info.stack.push("NextAuth"); }
    else if (allDeps["@supabase/auth-helpers-nextjs"] || allDeps["@supabase/ssr"]) { info.hasAuth = true; info.authName = "Supabase Auth"; info.stack.push("Supabase Auth"); }
    else if (allDeps["firebase"]) { info.hasAuth = true; info.authName = "Firebase Auth"; info.stack.push("Firebase"); }

    // Payments
    if (allDeps["stripe"]) { info.hasPayments = true; info.paymentName = "Stripe"; info.stack.push("Stripe"); }
    else if (allDeps["@paddle/paddle-js"]) { info.hasPayments = true; info.paymentName = "Paddle"; info.stack.push("Paddle"); }
    else if (allDeps["@tosspayments/payment-sdk"]) { info.hasPayments = true; info.paymentName = "Toss Payments"; info.stack.push("Toss Payments"); }

    // AI providers
    if (allDeps["openai"]) { info.hasAI = true; info.stack.push("OpenAI"); }
    else if (allDeps["@anthropic-ai/sdk"]) { info.hasAI = true; info.stack.push("Anthropic"); }
    else if (allDeps["@google/generative-ai"]) { info.hasAI = true; info.stack.push("Google AI"); }
  } catch { /* no package.json — leave info empty */ }

  // Deploy target — sniffed from config files.
  if (await exists(join(process.cwd(), "vercel.json")) || await exists(join(process.cwd(), ".vercel"))) info.deploy = "Vercel";
  else if (await exists(join(process.cwd(), "netlify.toml"))) info.deploy = "Netlify";
  else if (await exists(join(process.cwd(), "fly.toml"))) info.deploy = "Fly.io";
  else if (await exists(join(process.cwd(), "Dockerfile"))) info.deploy = "Docker";

  // Components (top-level only — deep scans are too noisy for this banner)
  try {
    const compsDir = join(process.cwd(), "src", "components");
    if (await exists(compsDir)) {
      const files = await readdir(compsDir);
      info.components = files
        .filter(f => f.endsWith(".tsx") || f.endsWith(".vue") || f.endsWith(".svelte"))
        .map(f => f.replace(/\.\w+$/, ""));
    }
  } catch { /* missing dir — ignore */ }

  // App Router API routes (recursive scan)
  try {
    const apiDir = join(process.cwd(), "src", "app", "api");
    if (await exists(apiDir)) {
      const scanDir = async (dir, prefix = "") => {
        const entries = await readdir(dir, { withFileTypes: true });
        const routes = [];
        for (const e of entries) {
          if (e.isDirectory()) routes.push(...await scanDir(join(dir, e.name), `${prefix}/${e.name}`));
          else if (e.name === "route.ts" || e.name === "route.js") routes.push(prefix || "/");
        }
        return routes;
      };
      info.apiRoutes = await scanDir(apiDir);
    }
  } catch { /* missing dir — ignore */ }

  // i18n locale files (first matching directory wins)
  try {
    for (const localeDir of ["src/i18n/dictionaries", "src/locales", "locales", "messages", "public/locales"]) {
      const dir = join(process.cwd(), localeDir);
      if (await exists(dir)) {
        const files = await readdir(dir);
        info.locales = files.filter(f => f.endsWith(".json")).map(f => f.replace(".json", ""));
        break;
      }
    }
  } catch { /* missing dir — ignore */ }

  return info;
}
