/**
 * Unit tests for lib/cli/templates.js
 *
 * detectProject() reads the current working directory. We exercise it by
 * writing a synthetic project tree to a tmp dir and chdir-ing into it.
 * Each test restores the original cwd in afterEach so suites stay isolated.
 */
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { detectProject, TEMPLATES } from '../lib/cli/templates.js';

let tmp;
let originalCwd;

beforeEach(() => {
  originalCwd = process.cwd();
  tmp = mkdtempSync(join(tmpdir(), 'buildcrew-tpl-test-'));
  process.chdir(tmp);
});

afterEach(() => {
  process.chdir(originalCwd);
  rmSync(tmp, { recursive: true, force: true });
});

describe('TEMPLATES registry', () => {
  it('exposes 9 templates total', () => {
    expect(Object.keys(TEMPLATES)).toHaveLength(9);
  });

  it('project and rules are core (auto-generated by init)', () => {
    expect(TEMPLATES.project.category).toBe('core');
    expect(TEMPLATES.project.file).toBeNull();
    expect(TEMPLATES.rules.category).toBe('core');
    expect(TEMPLATES.rules.file).toBeNull();
  });

  it('every non-core template references a real file', () => {
    for (const [name, t] of Object.entries(TEMPLATES)) {
      if (t.category === 'core') continue;
      expect(t.file, `${name} should reference a file`).toBeTruthy();
      expect(t.file).toMatch(/\.md$/);
    }
  });

  it('every template has a non-empty description', () => {
    for (const [name, t] of Object.entries(TEMPLATES)) {
      expect(t.desc, `${name} should have desc`).toBeTruthy();
      expect(t.desc.length).toBeGreaterThan(0);
    }
  });
});

describe('detectProject — empty project', () => {
  it('returns the default shape with empty fields', async () => {
    const info = await detectProject();
    expect(info.name).toBe('');
    expect(info.framework).toBe('');
    expect(info.stack).toEqual([]);
    expect(info.hasTS).toBe(false);
    expect(info.hasDB).toBe(false);
    expect(info.components).toEqual([]);
    expect(info.apiRoutes).toEqual([]);
    expect(info.locales).toEqual([]);
  });
});

describe('detectProject — Next.js + TS + Tailwind', () => {
  beforeEach(() => {
    writeFileSync(join(tmp, 'package.json'), JSON.stringify({
      name: 'demo', description: 'a demo app',
      dependencies: { next: '14.0.0', react: '18.0.0' },
      devDependencies: { typescript: '5.0.0', tailwindcss: '3.0.0' },
    }));
  });

  it('detects framework, TS, Tailwind', async () => {
    const info = await detectProject();
    expect(info.name).toBe('demo');
    expect(info.description).toBe('a demo app');
    expect(info.framework).toBe('Next.js');
    expect(info.hasTS).toBe(true);
    expect(info.hasTailwind).toBe(true);
    expect(info.stack).toContain('Next.js');
    expect(info.stack).toContain('TypeScript');
    expect(info.stack).toContain('TailwindCSS');
  });
});

describe('detectProject — auth/db/payments/AI', () => {
  beforeEach(() => {
    writeFileSync(join(tmp, 'package.json'), JSON.stringify({
      name: 'fullstack',
      dependencies: {
        next: '14.0.0',
        '@supabase/supabase-js': '2.0.0',
        '@supabase/ssr': '0.0.1',
        stripe: '14.0.0',
        openai: '4.0.0',
      },
    }));
  });

  it('detects supabase auth+db, stripe, openai', async () => {
    const info = await detectProject();
    expect(info.hasDB).toBe(true);
    expect(info.dbName).toBe('Supabase');
    expect(info.hasAuth).toBe(true);
    expect(info.authName).toBe('Supabase Auth');
    expect(info.hasPayments).toBe(true);
    expect(info.paymentName).toBe('Stripe');
    expect(info.hasAI).toBe(true);
    expect(info.stack).toContain('OpenAI');
  });
});

describe('detectProject — deploy detection', () => {
  it('detects Vercel from vercel.json', async () => {
    writeFileSync(join(tmp, 'vercel.json'), '{}');
    const info = await detectProject();
    expect(info.deploy).toBe('Vercel');
  });

  it('detects Netlify from netlify.toml', async () => {
    writeFileSync(join(tmp, 'netlify.toml'), '');
    const info = await detectProject();
    expect(info.deploy).toBe('Netlify');
  });

  it('detects Docker from Dockerfile when nothing else matches', async () => {
    writeFileSync(join(tmp, 'Dockerfile'), 'FROM node:20');
    const info = await detectProject();
    expect(info.deploy).toBe('Docker');
  });
});

describe('detectProject — components & api routes', () => {
  it('lists tsx/vue/svelte components from src/components', async () => {
    mkdirSync(join(tmp, 'src', 'components'), { recursive: true });
    writeFileSync(join(tmp, 'src', 'components', 'Button.tsx'), '');
    writeFileSync(join(tmp, 'src', 'components', 'Card.vue'), '');
    writeFileSync(join(tmp, 'src', 'components', 'README.md'), ''); // ignored
    const info = await detectProject();
    expect(info.components.sort()).toEqual(['Button', 'Card']);
  });

  it('walks app router api directory', async () => {
    mkdirSync(join(tmp, 'src', 'app', 'api', 'users'), { recursive: true });
    mkdirSync(join(tmp, 'src', 'app', 'api', 'health'), { recursive: true });
    writeFileSync(join(tmp, 'src', 'app', 'api', 'users', 'route.ts'), '');
    writeFileSync(join(tmp, 'src', 'app', 'api', 'health', 'route.js'), '');
    const info = await detectProject();
    expect(info.apiRoutes.sort()).toEqual(['/health', '/users']);
  });

  it('detects locales from messages/ directory', async () => {
    mkdirSync(join(tmp, 'messages'), { recursive: true });
    writeFileSync(join(tmp, 'messages', 'en.json'), '{}');
    writeFileSync(join(tmp, 'messages', 'ko.json'), '{}');
    const info = await detectProject();
    expect(info.locales.sort()).toEqual(['en', 'ko']);
  });
});

describe('detectProject — invalid package.json is non-fatal', () => {
  it('returns empty info without throwing', async () => {
    writeFileSync(join(tmp, 'package.json'), 'not json');
    const info = await detectProject();
    expect(info.name).toBe('');
    expect(info.framework).toBe('');
  });
});
